baseURL = 'https://aliciacyy.github.io/trailblazer'
languageCode = 'en-us'
title = "Trailblazer's Path"
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there."
Content = "Adding more stuff soon."
