name: Add New Post Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write 
  
jobs:
  pre-hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Read latest commit message
        id: commit_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          # Split the commit message
          read -r DATE DISTANCE HEART_RATE PACE TIME TITLE <<< "$COMMIT_MSG"
          
          # Validate date format (YYYY-MM-DD)
          if ! [[ $DATE =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Error: Date format is incorrect. Expected format: YYYY-MM-DD"
            echo "Received date: $DATE"
            exit 1
          fi
          
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "DISTANCE=$DISTANCE" >> $GITHUB_ENV
          echo "HEART_RATE=$HEART_RATE" >> $GITHUB_ENV
          echo "PACE=$PACE" >> $GITHUB_ENV
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV

      - name: Run Python script with extracted values
        run: |
          python3 scripts/create_post.py "$DATE" "$DISTANCE" "$HEART_RATE" "$PACE" "$TIME" "$TITLE"

      - name: Run Python script to update values
        run: |
          python3 scripts/count_posts.py

      - name: Run Python script to update HTML
        run: |
          python3 scripts/update_stats_in_html.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add content/posts/
          git add data/stats.json
          git add layouts/partials/home_info.html
          git commit -m "[skip ci] Update stats and add new post" || echo "No changes to commit"
          git push

  call-hugo:
    needs: pre-hugo
    uses: ./.github/workflows/hugo.yaml
